### ISSUE TITLE
Chat send response parsing

### ISSUE THREAD

**Issue by daBee** [dpaluy/chat_gpt#17]
I'm getting an error upon parsing the response:

code:
```
a = ChatGpt::Api.new
r = a.send(query)              # 
total_tokens = r['usage']['total_tokens']
responses = r['choices'].map { |c| c['text'] }

```

Error:
```
/Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/chat_gpt-0.1.1/lib/chat_gpt/api.rb:32:in `parse_resonse': undefined method `[]' for nil:NilClass (NoMethodError)

        conversation_id: response[0]["conversation_id"],
                                 ^^^
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/chat_gpt-0.1.1/lib/chat_gpt/api.rb:24:in `send'
	from /users/user3/app.rb:1637:in `get_gpt_response'
	from /users/user3/app.rb:1651:in `<main>'
```

It looks like a typo: `parse_resonse`.  Just had a look...no typo.  

Mind you, `openai` has had issues today, so no response might be actually happening.

**Comment by jx-bamboo** [comment]
NoMethodError (undefined method `[]' for nil:NilClass

        conversation_id: response[0]["conversation_id"],
                                 ^^^):

app/controllers/home_controller.rb:58:in `test'

**Comment by daBee** [comment]
Seems it's abandoned.
